# 此工作流的名字
name: Build 
# 工作流的执行时机，可以设定为定时执行，每次push后执行，手动执行等
on:
  # workflow_dispatch为在Github仓库的Actions面板中手动执行
  workflow_dispatch:
# 工作/任务，这里的工作是可以并行的。
jobs:
  # Mac系统打包
  buildmac:
    # 运行的操作系统 最新的macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version : '16'
      - name: Install and Build
        run:
          npm install && cd frontend && npm install && cd .. && npm run pak
       # 步骤二的名称：将编译后的结果上传
      - name: Upload to oss
        id: upload_to_oss
        uses: wxh06/dist2oss@v1
        with:
          version: "6.7.6"
          stable: true
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-us-west-1
          bucket: ullrai
          assets: |
            out/*dmg
            out/latest.yml
            out/*blockmap
  
